import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";

import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ali&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-4 md:px-16 lg:px-32 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-8 mb-8 flex justify-between">
            <h1 className="text-xl font-burtons text-gray-800 dark:text-white">
              DevelopedByAli
            </h1>
            <ul className="flex items-center">
              <li onClick={() => setDarkMode(!darkMode)}>
                {darkMode ? (
                  <BsFillSunFill className="text-white cursor-pointer text-2xl" />
                ) : (
                  <BsFillMoonStarsFill className="text-gray-800 cursor-pointer text-2xl" />
                )}
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-6"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-6">
            <h2 className="text-4xl py-2 text-teal-600 font-medium md:text-5xl lg:text-6xl">
              Ali Radmanesh
            </h2>
            <h3 className="text-xl py-2 md:text-2xl lg:text-3xl dark:text-white">
              Developer and Designer
            </h3>
            <p className="text-md py-4 leading-7 text-gray-800 md:text-lg lg:text-xl max-w-xl mx-auto dark:text-white">
              Freelancer providing services for programming and design content
              needs. Join me down below and let&apos;s get cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-12 py-3 text-gray-600 dark:text-white">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96">
            <Image
              src={deved}
              alt="DevEd"
              fill={true}
              className="object-cover"
            />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-2xl pt-10 dark:text-white">Services I offer</h3>
            <p className="text-md py-4 leading-7 text-gray-800 dark:text-white">
              Since the beginning of my journey as a freelance designer and
              developer, I&apos;ve done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500"> startups </span>
              and collaborated with talented people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-7 text-gray-800 dark:text-white">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex lg:gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-6 dark:bg-white">
              <Image
                src={design}
                alt=""
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-6 dark:bg-white">
              <Image
                src={code}
                alt=""
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-6 dark:bg-white">
              <Image
                src={consulting}
                alt=""
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-2xl pt-2 dark:text-white">Portfolio</h3>
            <p className="text-md py-4 leading-7 text-gray-800 dark:text-white">
              Since the beginning of my journey as a freelance designer and
              developer, I&apos;ve done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500"> startups </span>
              and collaborated with talented people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-7 text-gray-800 dark:text-white">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                alt="Portfolio #1"
                className="rounded-lg object-cover w-full h-full"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                alt="Portfolio #2"
                className="rounded-lg object-cover w-full h-full"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                alt="Portfolio #3"
                className="rounded-lg object-cover w-full h-full"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                alt="Portfolio #4"
                className="rounded-lg object-cover w-full h-full"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                alt="Portfolio #5"
                className="rounded-lg object-cover w-full h-full"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                alt="Portfolio #6"
                className="rounded-lg object-cover w-full h-full"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
